openapi: 3.0.0
info:
  version: 1.0.0
  title: Empayre Openapi API
  description:
    $ref: './docs/api.md'
  termsOfService: http://empayre/
  contact:
    name: Empayre support team
    email: support@empayre
    url: 'https://developer.empayre'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://{subdomain}.empayre/openapi/{version}'
    variables:
      subdomain:
        default: api
      version:
        enum:
          - v1
        default: v1
security:
  - bearer: []
components:
  securitySchemes:
    bearer:
      $ref: './components/security-schemes/Bearer.yaml'
